### ISSUE TITLE
Would it be cleaner?

### ISSUE THREAD

**Issue by aligoren** [frost-js/fquery#1]
Hi. In below code looks a repeated piece of code.

https://github.com/elusivecodes/FrostDOM/blob/7b3e8e65237e0dcf954b6b9a1b1746ef0e5706ae/src/DOM/ajax/scripts.js#L27-L37

## Suggested Method

```js
loadScripts(scripts, cache = true) {
    return scripts.map(script =>
        loadScript(script, cache)
    )
}
```

I'm not sure if this will work with this method.

**Comment by elusivecodes** [comment]
Hi, thanks for the suggestion!

With the current implementation, the scripts are loaded simultaneously, but executed in order, which is useful for cases when a script depends on another script already being loaded.

Consider the case: *script.js* relies on *dependency.js* already being loaded.

```javascript
dom.loadScripts(['dependency.js', 'script.js']);
```

With the suggested method, the order of script execution is not guaranteed.. in some cases this doesn't matter, but for this method I'd prefer to retain the order of execution.

Of course, you could load dependencies first, but this would mean the second script has to wait until the first script is loaded before starting the request.

```javascript
dom.loadScript('dependency.js').then(_ => dom.loadScript('script.js'));
```

Appreciate you checking out the code!

**Comment by aligoren** [comment]
I understood now. I missed it.

Thanks.

Thank you I like your all repositories.
